const SUPABASE_URL='https://iqimalzzfqcaynxrahyv.supabase.co';const SUPABASE_KEY='sb_publishable_Zz1kalj49bNKwZqfXBkRvg_WVZyP12q';const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=s=>document.querySelector(s);const loginView=$('#loginView'),adminView=$('#adminView'),editor=$('#editor'),status=$('#status');let rows=[];
const groups={Abertura:['opening.names','opening.date'],Capa:['hero.eyebrow','hero.save','hero.names','hero.date','hero.place'],Convite:['welcome.eyebrow','welcome.title','welcome.body','photo.1','photo.1.caption'],Citações:['quote.bible','quote.reference'],Data:['event.datetime','date.eyebrow','date.title','date.day','date.month','date.weekday'],Detalhes:['details.ceremony.time','details.ceremony.venue','details.ceremony.city','details.location.url','details.celebration.title','details.celebration.venue','details.dress.title','details.support.phone'],Galeria:['gallery.1','gallery.1.caption','gallery.2','gallery.2.caption','photo.2','photo.2.caption'],Inspiração:['inspiration.label','inspiration.quote1','inspiration.author1','inspiration.quote2','inspiration.author2'],Mensagem:['guestbook.title','guestbook.body'],Confirmação:['rsvp.title','rsvp.body'],Contactos:['whatsapp.phone'],Rodapé:['footer.text']};
async function load(){const {data,error}=await sb.from('invitation_content').select('*').order('sort_order');if(error){show(error.message,true);return}rows=data||[];render()}
function show(m,err=false){status.textContent=m;status.style.display='block';status.style.borderLeftColor=err?'#9b3d3d':'var(--green)';setTimeout(()=>status.style.display='none',5000)}
function row(k){return rows.find(x=>x.field_key===k)}
function render(){editor.innerHTML=Object.entries(groups).map(([g,keys])=>'<section class="section"><div class="section-head"><h2>'+g+'</h2></div><div class="fields">'+keys.map(fieldHtml).join('')+'</div></section>').join('');editor.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveField(b.dataset.save));editor.querySelectorAll('[data-upload]').forEach(b=>b.onchange=e=>uploadImage(b.dataset.upload,e.target.files[0]))}
function fieldHtml(k){const r=row(k);if(!r)return'';if(r.value_type==='image')return '<div class="field"><label>'+r.label+'</label><div class="image-box"><img src="'+(r.value||'')+'" alt=""><div class="image-actions"><input type="file" accept="image/*" data-upload="'+k+'"><button type="button" onclick="clearImage(\''+k+'\')">Remover</button></div></div></div>';return '<div class="field"><label>'+r.label+'</label><div class="field-row"><textarea id="f-'+k+'" rows="2">'+esc(r.value)+'</textarea><button class="save" data-save="'+k+'">Guardar</button></div><small>Campo: '+k+'</small></div>'}
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
async function saveField(k){const v=$('#f-'+k)?.value??'';const {error}=await sb.from('invitation_content').update({value:v,updated_at:new Date().toISOString()}).eq('field_key',k);if(error)return show(error.message,true);row(k).value=v;show('Alteração guardada: '+row(k).label)}
async function uploadImage(k,file){if(!file)return;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path='wedding/'+k.replaceAll('.','/')+'-'+crypto.randomUUID()+'.'+ext;show('A enviar imagem…');const up=await sb.storage.from('invitation-media').upload(path,file,{contentType:file.type,upsert:false});if(up.error)return show(up.error.message,true);const url=sb.storage.from('invitation-media').getPublicUrl(path).data.publicUrl;const {error}=await sb.from('invitation_content').update({value:url,updated_at:new Date().toISOString()}).eq('field_key',k);if(error)return show(error.message,true);row(k).value=url;render();show('Imagem atualizada: '+row(k).label)}
async function clearImage(k){const {error}=await sb.from('invitation_content').update({value:'',updated_at:new Date().toISOString()}).eq('field_key',k);if(error)return show(error.message,true);row(k).value='';render();show('Imagem removida.')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const email=$('#email').value.trim();const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});$('#loginMsg').textContent=error?error.message:'Link de acesso enviado. Verifica o teu email.'};
$('#logout').onclick=()=>sb.auth.signOut();
async function init(){const {data}=await sb.auth.getSession();if(data.session){loginView.classList.add('hidden');adminView.classList.remove('hidden');await load()}}
sb.auth.onAuthStateChange((_e,session)=>{if(session){loginView.classList.add('hidden');adminView.classList.remove('hidden');load()}else{loginView.classList.remove('hidden');adminView.classList.add('hidden')}});init();