const SUPABASE_URL='https://iqimalzzfqcaynxrahyv.supabase.co';const SUPABASE_KEY='sb_publishable_Zz1kalj49bNKwZqfXBkRvg_WVZyP12q';const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=s=>document.querySelector(s);const loginView=$('#loginView'),adminView=$('#adminView'),editor=$('#editor'),status=$('#status');let rows=[];const pendingImages={};const groups={Abertura:['opening.names','opening.date'],Capa:['hero.eyebrow','hero.save','hero.names','hero.date','hero.place'],Convite:['welcome.eyebrow','welcome.title','welcome.body','photo.1','photo.1.caption'],Citações:['quote.bible','quote.reference'],Data:['event.datetime','date.eyebrow','date.title','date.day','date.month','date.weekday'],Detalhes:['details.ceremony.time','details.ceremony.venue','details.ceremony.city','details.location.url','details.celebration.title','details.celebration.venue','details.dress.title','details.support.phone'],Galeria:['gallery.1','gallery.1.caption','gallery.2','gallery.2.caption','photo.2','photo.2.caption'],Inspiração:['inspiration.label','inspiration.quote1','inspiration.author1','inspiration.quote2','inspiration.author2'],Mensagem:['guestbook.title','guestbook.body'],Confirmação:['rsvp.title','rsvp.body'],Contactos:['whatsapp.phone'],Rodapé:['footer.text']};
async function load(){const {data,error}=await sb.from('invitation_content').select('*').order('sort_order');if(error){show(error.message,true);return}rows=data||[];render()}
function show(m,err=false){status.textContent=m;status.style.display='block';status.style.borderLeftColor=err?'#9b3d3d':'var(--green)';setTimeout(()=>status.style.display='none',5000)}
function row(k){return rows.find(x=>x.field_key===k)}
function render(){editor.innerHTML=Object.entries(groups).map(([g,keys])=>'<section class="section"><div class="section-head"><h2>'+g+'</h2><span>'+keys.filter(k=>row(k)).length+' campos</span></div><div class="fields">'+keys.map(fieldHtml).join('')+'</div></section>').join('');editor.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveField(b.dataset.save));editor.querySelectorAll('[data-upload]').forEach(b=>b.onchange=e=>previewImage(b.dataset.upload,e.target.files[0]));editor.querySelectorAll('[data-send-image]').forEach(b=>{b.style.display='inline-flex';b.style.visibility='visible';b.disabled=false;b.onclick=()=>uploadImage(b.dataset.sendImage,pendingImages[b.dataset.sendImage])});}
function fieldHtml(k){const r=row(k);if(!r)return'';if(r.value_type==='image')return '<div class="field image-field"><label>'+r.label+'</label><div class="image-box">'+(r.value?'<img src="'+escAttr(r.value)+'" alt="'+escAttr(r.label)+'"><div class="image-status">✓ Imagem adicionada</div>':'<div class="no-image">Sem imagem definida</div>')+'<div class="image-actions"><label class="upload"><input type="file" accept="image/*" data-upload="'+k+'">Escolher nova imagem</label><button type="button" class="image-save" style="display:inline-flex!important;visibility:visible!important;width:auto!important;margin-top:0!important;background:#18352b!important;color:#fff!important;border:1px solid #18352b!important;padding:10px 16px!important;cursor:pointer!important" data-send-image="'+k+'" >Guardar imagem</button>'+(r.value?'<button type="button" onclick="clearImage(\''+k+'\')">Remover imagem</button>':'')+'</div></div><small>Campo: '+k+'</small></div>';const type=k==='event.datetime'?'datetime-local':r.value_type==='url'?'url':k.includes('phone')?'tel':'text';const value=k==='event.datetime'?toLocal(r.value):r.value||'';return '<div class="field"><label for="f-'+k+'">'+r.label+'</label><div class="field-row">'+(type==='text'&&((r.value||'').length>100||k.includes('body')||k.includes('quote'))?'<textarea id="f-'+k+'" rows="4">'+esc(value)+'</textarea>':'<input id="f-'+k+'" type="'+type+'" value="'+escAttr(value)+'">')+'<button class="save" data-save="'+k+'">Guardar</button></div><small>Campo: '+k+'</small></div>'}
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')};function escAttr(s){return esc(s).replaceAll('"','&quot;')};function toLocal(v){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())+'T'+p(d.getHours())+':'+p(d.getMinutes())}
async function saveField(k){const el=$('#f-'+k);if(!el)return;let v=el.value;if(k==='event.datetime'&&v)v=new Date(v).toISOString();const {error}=await sb.from('invitation_content').update({value:v,updated_at:new Date().toISOString()}).eq('field_key',k);if(error)return show(error.message,true);row(k).value=v;show('Alteração guardada: '+row(k).label)}
function previewImage(k,file){if(!file)return;if(file.size>8*1024*1024)return show('A imagem deve ter no máximo 8 MB.',true);if(!file.type.startsWith('image/'))return show('Escolhe um ficheiro de imagem.',true);pendingImages[k]=file;const input=document.querySelector('[data-upload="'+k+'"]');const box=input?.closest('.image-box');if(box){const img=box.querySelector('img')||document.createElement('img');img.src=URL.createObjectURL(file);img.alt='Pré-visualização';if(!img.parentNode)box.insertBefore(img,box.firstChild);let p=box.querySelector('.preview-status');if(!p){p=document.createElement('div');p.className='preview-status';box.insertBefore(p,box.querySelector('.image-actions'));}p.textContent='Pré-visualização pronta — clique em “Guardar imagem”';const btn=box.querySelector('[data-send-image]');if(btn){btn.disabled=false;btn.textContent='Guardar imagem';}}show('Pré-visualização pronta. Clique em “Guardar imagem”.')}
async function uploadImage(k,file){if(!file)return show('Primeiro escolha uma imagem.',true);if(file.size>8*1024*1024)return show('A imagem deve ter no máximo 8 MB.',true);if(!file.type.startsWith('image/'))return show('Escolhe um ficheiro de imagem.',true);show('A enviar imagem…');const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path='wedding/'+k.replaceAll('.','/')+'-'+crypto.randomUUID()+'.'+ext;const up=await sb.storage.from('invitation-media').upload(path,file,{contentType:file.type,upsert:false});if(up.error)return show(up.error.message,true);const url=sb.storage.from('invitation-media').getPublicUrl(path).data.publicUrl;const saved=await sb.from('invitation_content').update({value:url,updated_at:new Date().toISOString()}).eq('field_key',k).select('field_key,value').maybeSingle();if(saved.error)return show('A imagem foi enviada, mas não foi possível guardar o endereço: '+saved.error.message,true);if(!saved.data)return show('A imagem foi enviada, mas a alteração não foi autorizada para este administrador. Verifique o acesso do Admin.',true);row(k).value=saved.data.value||url;delete pendingImages[k];render();show('✓ Imagem guardada. Ao atualizar a página, esta mesma imagem continuará aqui.');}
async function clearImage(k){const {error}=await sb.from('invitation_content').update({value:'',updated_at:new Date().toISOString()}).eq('field_key',k);if(error)return show(error.message,true);row(k).value='';render();show('Imagem removida: '+row(k).label)}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const email=$('#email').value.trim();const password=$('#password').value;const btn=e.target.querySelector('button');btn.disabled=true;btn.textContent='A entrar…';const {error}=await sb.auth.signInWithPassword({email,password});btn.disabled=false;btn.textContent='Entrar no painel';$('#loginMsg').textContent=error?'Não foi possível iniciar sessão. Verifica os dados de acesso e a autorização do administrador.':''};
$('#logout').onclick=()=>sb.auth.signOut();async function init(){const {data}=await sb.auth.getSession();if(data.session){loginView.classList.add('hidden');adminView.classList.remove('hidden');await load();await loadGuests()}}sb.auth.onAuthStateChange((_e,session)=>{if(session){loginView.classList.add('hidden');adminView.classList.remove('hidden');load();loadGuests()}else{loginView.classList.remove('hidden');adminView.classList.add('hidden')}});init();
async function loadGuests(){
  const {data,error}=await sb.from('invitation_guests').select('*').order('created_at',{ascending:false});
  if(error){show(error.message,true);return}
  const list=$('#guestList'); if(!list)return;
  if(!data?.length){list.innerHTML='<div class="guest-empty">Ainda não há convidados personalizados.</div>';return}
  const base=window.location.origin+window.location.pathname.replace(/admin\.html$/,'');
  list.innerHTML=data.map(g=>{
    const names=g.guest_type==='couple'&&g.name2?esc(g.name1)+' &amp; '+esc(g.name2):esc(g.name1)+(g.name2?' &amp; '+esc(g.name2):'');
    const link=base+'?guest='+encodeURIComponent(g.token);
    const isSingle=g.guest_type==='single';
    const address=isSingle?'Querido(a) '+g.name1+',':'Queridos '+(g.guest_type==='couple'&&g.name2?g.name1+' & '+g.name2:g.name1)+',';
    const message='*“O que Deus uniu, ninguém o separe.”*\\n_— Marcos 10:9_ 🤍\\n\\n'+address+'\\n\\nHá momentos que passam… e há momentos que ficam para sempre no coração.\\n\\nA nossa história trouxe-nos até aqui, e agora estamos prestes a viver um dos capítulos mais bonitos das nossas vidas. ❤️\\n\\nNo dia *05 de Dezembro de 2026*, vamos celebrar o nosso amor, a nossa união e o começo de uma nova vida juntos. 💍✨\\n\\n'+(isSingle?'Queremos muito ter-te connosco':'Queremos muito ter-vos connosco')+' nesse dia tão especial, porque as pessoas que amamos fazem parte da nossa história. 🤍\\n\\n*Guarda esta data com carinho.*\\nO nosso grande dia está a chegar… ✨\\n\\nPreparamos este pequeno convite especialmente para '+(isSingle?'ti':'vocês')+', com todo o nosso amor. 💌\\n\\n🔗 *O NOSSO CONVITE*\\n'+link+'\\n\\nCom amor,\\n*Irina & Edson* ❤️';
    const wa='https://wa.me/?text='+encodeURIComponent(message);
    return '<article class="guest-card"><div><strong>'+names+'</strong><span>'+guestTypeLabel(g.guest_type)+' · '+g.guest_count+' pessoa(s)</span><span class="guest-link">'+esc(link)+'</span></div><div class="guest-actions"><select data-rsvp="'+g.id+'"><option value="pending" '+(g.rsvp_status==='pending'?'selected':'')+'>Pendente</option><option value="confirmed" '+(g.rsvp_status==='confirmed'?'selected':'')+'>Confirmado</option><option value="declined" '+(g.rsvp_status==='declined'?'selected':'')+'>Não poderá ir</option></select><button type="button" data-copy="'+escAttr(link)+'">Copiar link</button><button type="button" data-message="'+escAttr(message)+'">Copiar mensagem</button><a class="guest-wa" href="'+escAttr(wa)+'" target="_blank" rel="noopener">Enviar WhatsApp</a><button type="button" data-delete="'+g.id+'">Apagar</button></div></article>'
  }).join('');
  list.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);show('✓ Link copiado para enviar ao convidado.')});
  list.querySelectorAll('[data-message]').forEach(b=>b.onclick=async()=>{const message=buildGuestMessage(b.dataset.message);await navigator.clipboard.writeText(message);show('✓ Mensagem actualizada copiada com o link personalizado.')});
  list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteGuest(b.dataset.delete));
  list.querySelectorAll('[data-rsvp]').forEach(s=>s.onchange=()=>updateGuestStatus(s.dataset.rsvp,s.value));
}
function guestTypeLabel(t){return ({single:'Uma pessoa',couple:'Casal',family:'Família',group:'Grupo'})[t]||t}
async function addGuest(){
  const type=$('#guestType').value,name1=$('#guestName1').value.trim(),name2=$('#guestName2').value.trim(),count=Math.max(1,Math.min(20,Number($('#guestCount').value)||1));
  if(!name1)return show('Indica pelo menos o primeiro nome.',true);
  const token=crypto.randomUUID().replaceAll('-','').slice(0,16);
  const {error}=await sb.from('invitation_guests').insert({token,guest_type:type,name1,name2,guest_count:count});
  if(error)return show(error.message,true);
  $('#guestName1').value='';$('#guestName2').value='';$('#guestCount').value=type==='single'?1:2;
  await loadGuests();show('✓ Convidado criado e link personalizado gerado.');
}
async function updateGuestStatus(id,statusValue){
  const {error}=await sb.from('invitation_guests').update({rsvp_status:statusValue,updated_at:new Date().toISOString()}).eq('id',id);
  if(error)show(error.message,true);else show('Estado da confirmação actualizado.');
}
async function deleteGuest(id){
  if(!confirm('Apagar este convidado e o respectivo link?'))return;
  const {error}=await sb.from('invitation_guests').delete().eq('id',id);
  if(error)return show(error.message,true);
  await loadGuests();show('Convidado removido.');
}
document.addEventListener('DOMContentLoaded',()=>{
  $('#addGuest')?.addEventListener('click',addGuest);
  $('#guestType')?.addEventListener('change',()=>{const t=$('#guestType').value;$('#guestCount').value=t==='single'?1:t==='couple'?2:2});
});